version: '3.9'

services:
  # =========================
  # Postgresql Database
  # =========================
  postgres:
    image: postgres:16
    container_name: medcon-db
    environment:
      POSTGRES_DB: medcon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # =========================
  # Spring Boot Backend
  # =========================
  #  backend-springboot:
  #    build:
  #      context: ./backend-springboot
  #      dockerfile: Dockerfile
  #    container_name: medcon-api
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medcon
  #      SPRING_DATASOURCE_USERNAME: medcon_user
  #      SPRING_DATASOURCE_PASSWORD: medcon_pass
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      - postgres

  # =========================
  # Node.js WebSocket Server
  # =========================
  #  backend-nodejs:
  #    build:
  #      context: ./backend-nodejs
  #      dockerfile: Dockerfile
  #    container_name: medcon-realtime
  #    environment:
  #      PORT: 3001
  #    ports:
  #      - "3001:3001"

  # =========================
  # Angular Frontend with NGINX
  # =========================
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: medcon-frontend
#    ports:
#      - "4200:80"
#    depends_on:
#      - backend-springboot
#      - backend-nodejs

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
