server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medcon
    username: medcon_user
    password: medcon_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: medconSuperSecretKey123

