server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medcon
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: medconSuperSecretKey123NLKLKWE878954NLKFKL598348SNF3MSDFN894534DF7SDNF84

